In [1]:
import pandas as pd

In [2]:
path = r"C:\Users\User\dev\training_model\gdelt_data_fetch\gdelt_data.csv"
df = pd.read_csv(path)
df.head()

       date                                               text
0  20140101  The gold market in early 2014 saw a mix of cri...
1  20140102  Gold prices are starting strong in 2014, build...
2  20140103  Gold extends gains to reach two-week high as e...
3  20140104  Indian gold premiums are decreasing as wedding...
4  20140105  Here are the topics extracted from the provide...

In [3]:
df.tail()

         date                                               text
146  20140531  Here's a summary of the gold market situation ...
147  20140601  Gold is experiencing a testing time as hedge f...
148  20140602  Gold prices experienced their longest losing s...
149  20140603  Gold prices rebounded slightly in Asia, driven...
150  20140604  Several companies reported the presence of Nor...

In [4]:
path = r"C:\Users\User\dev\training_model\gdelt_data_fetch\gdelt_data1.csv"
df1 = pd.read_csv(path)
df1.head()

       date                                               text
0  20140605  Gold prices are expected to rise due to ECB st...
1  20140606  Gold prices are expected to rise due to ECB st...
2  20140607  Gold spot premiums fell as the market started ...
3  20140608  Gold spot premiums fell as the market started ...
4  20140609  Gold prices experienced a tumble in futures tr...

In [5]:
df1.tail()

         date                                               text
565  20151222  Randgold Resources has ended its joint venture...
566  20151223  Fuel is being sold at very high prices in Kano...
567  20151224  Fuel is being sold at very high prices in Kano...
568  20151225  Gold Fields Limited is forecasted to post FY20...
569  20151226  Gold Fields Limited is forecasted to post FY20...

In [6]:
path = r"C:\Users\User\dev\training_model\gdelt_data_fetch\gdelt_data2.csv"
df2 = pd.read_csv(path)
df2.head()

       date                                               text
0  20151226  Here's a summary of gold-related news based on...
1  20151227  Here's a summary of gold-related news based on...
2  20151228  Several reports discuss gold smuggling attempt...
3  20151229  Several reports discuss gold smuggling attempt...
4  20151230  Here's a summary of gold market news from the ...

In [7]:
df2.tail()

         date                                               text
179  20160622  Gold prices experienced a loss as chances of B...
180  20160623  Gold prices saw the biggest gain since 2008 du...
181  20160624  Gold prices saw the biggest gain since 2008 du...
182  20160625  Gold rallied to a 2-year high after Brexit, as...
183  20160626  Gold rallied to a 2-year high after Brexit, as...

In [22]:
path = r"C:\Users\User\dev\training_model\gdelt_data_fetch\gdelt_data3_1.csv"
df3 = pd.read_csv(path)
df3.head()

       date                                               text
0  20160627  Doug Casey warns of a coming crisis this year,...
1  20160628  Doug Casey warns of a coming crisis this year,...
2  20160629  Gold prices are expected to rally due to Brexi...
3  20160630  Gold prices are expected to rally due to Brexi...
4  20160701  Gold prices steadied as equity markets calmed....

In [23]:
df3.tail()

         date                                               text
119  20161024  Police in Kutch, India, apprehended three indi...
120  20161025  -Customs officials seized gold bars worth Rs 2...
121  20161026  -Customs officials seized gold bars worth Rs 2...
122  20161027  Third quarter earnings reports from major gold...
123  20161028  Third quarter earnings reports from major gold...

In [10]:
path = r"C:\Users\User\dev\training_model\gdelt_data_fetch\gdelt_data4.csv"
df4 = pd.read_csv(path)
df4.head()

       date                                               text
0  20161029  Dubai Gold and Commodities Exchange is opening...
1  20161030  Dubai Gold and Commodities Exchange is opening...
2  20161031  Gold rates in Vietnam and Egypt edged up due t...
3  20161101  Gold rates in Vietnam and Egypt edged up due t...
4  20161102  Customs officials seized 14 kg of gold at Dhak...

In [11]:
df4.tail()

         date                                               text
189  20170506  India's gold demand recovers with a 15% jump i...
190  20170507  New precious metal laws are being implemented ...
191  20170508  New precious metal laws are being implemented ...
192  20170509  Here's a summary of gold-related news based on...
193  20170510  Here's a summary of gold-related news based on...

In [12]:
path = r"C:\Users\User\dev\training_model\gdelt_data_fetch\gdelt_data5.csv"
df5 = pd.read_csv(path)
df5.head()

       date                                               text
0  20170510  China's private investor gold demand is surgin...
1  20170511  China's private investor gold demand is surgin...
2  20170512  Transition Metals Corp closes private placemen...
3  20170513  Transition Metals Corp closes private placemen...
4  20170514  Customs officials in Bangladesh seized 300 kg ...

In [13]:
df5.tail()

          date                                               text
2990  20250806  Gold prices are rising due to concerns over po...
2991  20250807  Gold prices are rising due to concerns over po...
2992  20250808  Gold futures experienced a surge to a record h...
2993  20250809  Gold futures experienced a surge to a record h...
2994  20250810  Gold futures experienced volatility due to con...

In [15]:
frames = [df, df1]

merged = pd.concat(frames)

merged.tail()

         date                                               text
565  20151222  Randgold Resources has ended its joint venture...
566  20151223  Fuel is being sold at very high prices in Kano...
567  20151224  Fuel is being sold at very high prices in Kano...
568  20151225  Gold Fields Limited is forecasted to post FY20...
569  20151226  Gold Fields Limited is forecasted to post FY20...

In [16]:
df2.head()

       date                                               text
0  20151226  Here's a summary of gold-related news based on...
1  20151227  Here's a summary of gold-related news based on...
2  20151228  Several reports discuss gold smuggling attempt...
3  20151229  Several reports discuss gold smuggling attempt...
4  20151230  Here's a summary of gold market news from the ...

In [17]:
df2 = df2.iloc[1:]
df2.head()

       date                                               text
1  20151227  Here's a summary of gold-related news based on...
2  20151228  Several reports discuss gold smuggling attempt...
3  20151229  Several reports discuss gold smuggling attempt...
4  20151230  Here's a summary of gold market news from the ...
5  20151231  Here's a summary of gold market news from the ...

In [18]:
merged = pd.concat([df2])

In [19]:
merged.tail()

         date                                               text
179  20160622  Gold prices experienced a loss as chances of B...
180  20160623  Gold prices saw the biggest gain since 2008 du...
181  20160624  Gold prices saw the biggest gain since 2008 du...
182  20160625  Gold rallied to a 2-year high after Brexit, as...
183  20160626  Gold rallied to a 2-year high after Brexit, as...

In [20]:
df5 = df5.iloc[1:]
frames = [df4, df5]
merged2 = pd.concat(frames)
print(merged2.head())
print(merged2.tail())

       date                                               text
0  20161029  Dubai Gold and Commodities Exchange is opening...
1  20161030  Dubai Gold and Commodities Exchange is opening...
2  20161031  Gold rates in Vietnam and Egypt edged up due t...
3  20161101  Gold rates in Vietnam and Egypt edged up due t...
4  20161102  Customs officials seized 14 kg of gold at Dhak...
          date                                               text
2990  20250806  Gold prices are rising due to concerns over po...
2991  20250807  Gold prices are rising due to concerns over po...
2992  20250808  Gold futures experienced a surge to a record h...
2993  20250809  Gold futures experienced a surge to a record h...
2994  20250810  Gold futures experienced volatility due to con...

In [25]:
merged = pd.concat([merged, df3])
merged.tail()

         date                                               text
119  20161024  Police in Kutch, India, apprehended three indi...
120  20161025  -Customs officials seized gold bars worth Rs 2...
121  20161026  -Customs officials seized gold bars worth Rs 2...
122  20161027  Third quarter earnings reports from major gold...
123  20161028  Third quarter earnings reports from major gold...

In [26]:
merged2.head()

       date                                               text
0  20161029  Dubai Gold and Commodities Exchange is opening...
1  20161030  Dubai Gold and Commodities Exchange is opening...
2  20161031  Gold rates in Vietnam and Egypt edged up due t...
3  20161101  Gold rates in Vietnam and Egypt edged up due t...
4  20161102  Customs officials seized 14 kg of gold at Dhak...

In [27]:
frames = [merged, merged2]
main = pd.concat(frames)
print(main.head())
print(main.tail())

       date                                               text
1  20151227  Here's a summary of gold-related news based on...
2  20151228  Several reports discuss gold smuggling attempt...
3  20151229  Several reports discuss gold smuggling attempt...
4  20151230  Here's a summary of gold market news from the ...
5  20151231  Here's a summary of gold market news from the ...
          date                                               text
2990  20250806  Gold prices are rising due to concerns over po...
2991  20250807  Gold prices are rising due to concerns over po...
2992  20250808  Gold futures experienced a surge to a record h...
2993  20250809  Gold futures experienced a surge to a record h...
2994  20250810  Gold futures experienced volatility due to con...

In [28]:
path = "../gdelt_gold_news_dataset.csv"
main.to_csv(path, index=False)